fooodie/urls.py
from django.urls import path
from fooodie import views
from django.conf.urls import url

app_name='fooodie'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('leaderboard/', views.leaderboard, name = 'leaderboard'),

    path('myprofile/', views.myprofile, name = 'myprofile'),
    path('myprofile/addfoodphoto/', views.addfoodphoto, name = 'addfoodphoto'),
    path('myprofile/settings/', views.usersettings, name = 'settings'),
    path('myprofile/settings/deletepic/<slug:photo_id>/', views.deletepic, name = 'deletepic'),
    path('myprofile/settings/password/', views.settingspassword, name='settingspassword'),
    path('myprofile/settings/username/', views.settingsusername, name = 'settingsusername'),
    path('myprofile/settings/profilepic/', views.settingsprofilepic, name = 'settingsprofilepic'),
    path('myprofile/settings/email/', views.settingsemail, name = 'settingsemail'),
    path('myprofile/settings/deleteaccount', views.deleteaccount, name='deleteaccount'),

    path('usersearch/', views.usersearch, name='usersearch'),
    path('user/<slug:user_profile_slug>/', views.userprofile, name='userprofile'),

    path('logout/', views.userlogout, name='logout'),
    path('login/', views.userlogin, name='login'),
    path('register/', views.register, name = 'register'),
    path('loginregister/', views.loginregister, name='loginregister'),
    path('googleloggedin/', views.googleloggedin, name='googleloggedin'),


    path('like_photo/', views.LikePhoto.as_view(), name = 'likephoto'),
    ]

wad2_group_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from fooodie import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('fooodie/', include('fooodie.urls')),
    path('', views.home, name='home'),
    path('', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fooodie/models.py
from django.db import models
from time import time
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
import factory  
import factory.django
        
class UserProfile(models.Model): 
    user = models.OneToOneField(User, on_delete=models.CASCADE) #Links UserProfile to a User model instance.  
    slug=models.SlugField(unique=True) #Slug field for when we try to view other user's profiles (Part of the urls)
    picture=models.ImageField(blank=True, upload_to=u'profilepics')
    #picture=models.ImageField(upload_to=str(id), blank=True)
    totalVotes = models.IntegerField(default=0)
    google=models.BooleanField(default=False)
    
    def set_picture(self, pic):
        pic.name=str(self.id)+".jpg"
        self.picture=pic
        self.save()
    
    def increase_votes(self, num):
        self.totalVotes=self.totalVotes+num
        self.save()

    def decrease_votes(self, num):
        self.totalVotes=self.totalVotes-num
        self.save()
    
    def save(self, *args, **kwargs):
        self.slug=slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)
        
    #We need to add __str__ method here

    # We store within a user the number of votes he has, each time someone votes on a photo we update both Photo.votes and UserProfile.totalVotes.
    # This way we only have to iterate through the list of UserProfile in the leaderboard.
    # When accessing a user's profile you just order the leaderboard using the totalVotes attribute and then iterate through it to find him.
    # Once you do his position on the list is his position in the ranking

class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = User
        #Here we tell the UserFactory to use the model User as a base,
        #this means it creates a User object and edits its following parameters:
    username = factory.Faker('user_name') #Changes "username" parameter of the user created above to a random "username", generated by the Faker function
    email = factory.Faker('email') #Changes "email" parameter of the user created above to a random "email", generated by the Faker function


""" 
These two functions are necessary to change the default folder
where photos are stored when uploaded by an user
"""

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/userProfile<id>
    return '{0}'.format(instance.userProfile.id)

def get_upload_filename(userpic,name):
    return u'%s/%s_%s' % (str(userpic.user.id),
                          str(time()).replace('.', '_'),
                          name)
        
class Photo(models.Model): 
    NAME_MAX_LENGTH=128
    name = models.CharField(max_length=NAME_MAX_LENGTH) #The name the user wants to give to the picture he has uploaded
    votes=models.IntegerField(default=0) #Number of votes the picture has
    user= models.ForeignKey(UserProfile, on_delete=models.CASCADE) #User which uploaded the photo, 1 to MANY relation, so primary key on MANY side
    photo = models.ImageField(blank=True, upload_to = get_upload_filename) #Uploaded photo
    date=models.DateField(auto_now=True)
    
    def __str__(self):
        return self.name
    
    def increase_votes(self, num):
        self.votes=self.votes+num
        self.user.increase_votes(num)
        self.save()
        
    def decrease_votes(self, num):
        self.votes=self.votes-num
        self.user.decrease_votes(num)
        self.save()

fooodie/forms.py
from django import forms
from fooodie.models import UserProfile, Photo
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

class UserSearchBarForm(forms.Form):
    username=forms.CharField()

class ChangeUsername(forms.Form):
    username=forms.CharField()

class ChangeEmail(forms.Form):
    email = forms.EmailField()

class ChangePicture(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

class PhotoForm(forms.ModelForm):
    class Meta:
        model=Photo
        fields=('name', 'photo',)

fooodie/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.conf import settings
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from fooodie.models import Photo, UserProfile
from fooodie.forms import UserForm, UserProfileForm, PhotoForm, ChangeUsername, ChangeEmail, ChangePicture
from datetime import datetime
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
import os, random, string
from django.views import View

#####################################HELPER FUNCTIONS START
def profile_leaderboard(profile):
    top_profiles_set = UserProfile.objects.order_by('-totalVotes')
    top_profiles = []
    position_leaderboard = 0
    profile_votes=['-1']
    for userprofile in top_profiles_set: #Creates new List containing tuples (UserProfile,Position)
        if profile_votes[len(profile_votes)-1]!=userprofile.totalVotes:
            position_leaderboard +=  1
        profile_votes.append(userprofile.totalVotes)
        if profile==userprofile:
            break
    return position_leaderboard

def get_user(request):
    return request.user
    
def get_profile(request):
    return UserProfile.objects.get(user=get_user(request))

def get_user_and_profile(request):
    user=get_user(request)
    profile=get_profile(request)
    return user, profile

#Returns two randomly-chosen Photo objects from the database
def random_dif_pics():
    pics = Photo.objects.order_by('?')
    pics_to_choose = pics[:2]
    pic1= pics_to_choose.first()
    pic2=pics_to_choose[1]
    if pic1==pic2:
        return random_dif_pics()
    return pic1, pic2

####################################HELPER FUNCTIONS END

###########VIEWS
def home(request):
    context_dict = {}
    pics = Photo.objects.order_by('?')
    try:
        photo1, photo2=random_dif_pics() #Returns two randomly-selected Photo objects into photo1 and photo2
        context_dict['photo1']=photo1
        context_dict['photo2']=photo2
        visitor_cookie_handler(request) #Tracks visit count and last visit time via a server-side cookie
        random_pics = pics[:3]
        context_dict['random_pics'] = random_pics
        context_dict['visits'] = request.session['visits'] #Obtains number of visits made this session
    except:
        return render(request, 'fooodie/error.html', context={'error' : "DEV NOTE: If this happens, it means there has been an issue when populating the database... Maybe you forgot to migrate or you didn't run the populate script. As long as you don't click on anything it is fine though. First stop running the server. Then go to your files and delete both [workspace]/fooodie/db.sqlite3, and [workspace]/fooodie/media with all its contents. Then in command line go to [workspace]/fooodie/ and first run 'python manage.py migrate', second run 'python populate_fooodie.py'. PLEASE DO NOT CLICK ON ANYTHING ON THE PAGE UNTIL YOU DO THIS. YOU'LL ONLY BREAK IT EVEN MORE"})
    return render(request, 'fooodie/home.html', context = context_dict)

def about(request):
    context_dict = {}
    response = render(request, 'fooodie/about.html')
    return(response)

def leaderboard(request):
    context_dict = {}
    top_pics = Photo.objects.order_by('-votes')[:3] #Top 3
    context_dict['top_pics'] = top_pics

    top_profiles_set = UserProfile.objects.order_by('-totalVotes')[:10] #Top 0 - 10
    top_profiles = []
    position_leaderboard = 0
    profile_votes=['-1']
    for profile in top_profiles_set: #Creates new List containing tuples (UserProfile,Position)
        if profile_votes[len(profile_votes)-1]!=profile.totalVotes:
            position_leaderboard +=  1
        top_profiles.append((profile,position_leaderboard))
        profile_votes.append(profile.totalVotes)

    context_dict['top_profiles'] = top_profiles

    response = render(request, 'fooodie/leaderboard.html', context = context_dict)
    return(response)

#REGISTRATION/LOG IN/LOG OUT STARTS
#This will simply display the forms; the associated template will call
#one of the functions below dependent on button clicked
def loginregister(request):
    if request.user.is_authenticated:
        return render(request, 'fooodie/error.html', context={'error':"You're already logged in. If you want to log in as someone else, please log out first."})
    registered = False
    user_form = UserForm()
    user_form.fields['username'].widget.attrs['maxlength']='20'
    profile_form = UserProfileForm()

    return render(request, 'fooodie/loginregister.html', context = {'user_form' : user_form,
                                                               'profile_form' : profile_form,
                                                               'registered' : registered})

def userlogin(request):
    if request.user.is_authenticated:
        return redirect(reverse('fooodie:loginregister'))
    user_form=UserForm()
    user_form.fields['username'].widget.attrs['maxlength']='20'
    profile_form=UserProfileForm()
    if request.method == 'POST': #If input data is being sent to the server
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(username = username, password = password) #Verifies credentials against user database, returns appropriate User object if valid
        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('fooodie:myprofile'))
            else:
                return render(request, 'fooodie/loginregister.html', context = {'user_form' : user_form, 'profile_form' : profile_form , 'login_error' : "Your account has been disabled. We'd apologize... But you probably did something to earn this.",})
        else:
            return render(request, 'fooodie/loginregister.html', context = {'user_form' : user_form, 'profile_form' : profile_form, 'login_error':"Invalid login details supplied."})
    else:
        return redirect(reverse('fooodie:loginregister'))

#Will focus on the registration/login logic first, implement into a single view later
def register(request):
    if request.user.is_authenticated:
        return redirect(reverse('fooodie:loginregister')) #Redirects back to login/register page if already logged in
    context_dict={}
    if request.method == 'POST': #If input data is being sent to the server
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid(): #Two forms make up the entire registration form and so must both be valid
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user
            profile.slug = user.username
            profile.save() #Profile must be saved in order to generate an id value to be used next

            if 'picture' in request.FILES:
                profile.set_picture(request.FILES['picture'])

            user.backend='django.contrib.auth.backends.ModelBackend'
            #Specify backend used for log in as we have 2 log in backends (Social and standard Django)
            login(request, user)
            return redirect(reverse('fooodie:myprofile'))

        else:
            context_dict['register_error']=user_form.errors
            user_form = UserForm()
            user_form.fields['username'].widget.attrs['maxlength']='20'
            context_dict['user_form'] = user_form
            context_dict['profile_form']=UserProfileForm()                
            return render(request, 'fooodie/loginregister.html', context = context_dict)
    else:
        return(redirect(reverse('fooodie:loginregister')))

@login_required
def userlogout(request):
    logout(request) # Since we know the user is logged in, we can now just log them out.
    return redirect(reverse('fooodie:home'))
#REGISTRATION/LOG IN/LOG OUT ENDS

#ADD AND DELETE PICTURE FUNCTIONALITY STARTS
@login_required
def addfoodphoto(request):
    profile=get_profile(request)
    context_dict = {}
    context_dict['profile'] = profile
    context_dict['photo_type']="food photo"
    context_dict['food']=True
    if request.method == 'POST':
        photo_form = PhotoForm(request.POST) # If the form is valid...
        if photo_form.is_valid(): # Save the photo form data to the database.
            # Now sort out the UserProfile instance. # Since we need to set the user attribute ourselves, we set commit=False. This delays saving the model
            # until we're ready to avoid integrity problems.
            try:
                photo = photo_form.save(commit=False)
                photo.user = profile # Did the user provide a profile picture? If so, we need to get it from the input form and put it in the UserProfile model.
                photo.photo = request.FILES['photo']
                # Now we save the UserProfile model instance.
                photo.save() # Update our variable to indicate that the template registration was successful.
                return redirect(reverse('fooodie:myprofile'))
            except:
                context_dict['error']="There was something wrong with your upload. Please try again. When this happens it's usually because you didn't upload a picture"
        else: # Invalid form or forms - mistakes or something else? Print problems to the terminal.
            context_dict['error']=photo_form.errors
    else: # Not a HTTP POST, so we render our form using two ModelForm instances. # These forms will be blank, ready for user input.
        photo_form = PhotoForm()
        photo_form.fields['name'].widget.attrs['maxlength']='20'

templates/fooodie/addPic.html
{% extends 'fooodie/base.html' %} 
{% load staticfiles %}
{% block title_block %}
Add a picture
{% endblock %} 
{% block body_block %}
<section class="section_padding_100_0 clearfix">
	<div id="fooodie-page">
		<a href="#" class="js-fooodie-nav-toggle fooodie-nav-toggle"><i></i></a>
		<aside id="fooodie-aside" role="complementary" class="text-center">
			{% if profile.picture %}
				<h1 id="fooodie-logo"><a href="/#"><span class="img" style="background-image: url({{ profile.picture.url}});"></span>{{ user.username }}</a></h1>
			{% else %}
				<h1 id="fooodie-logo"><a href="/#"><span class="img" style="background-image: url({% static 'images/defaultprofilefoto.jpg' %});"></span>{{ user.username }}</a></h1>
			{% endif %}
			<nav id="fooodie-main-menu" role="navigation">
				<ul>
					{% if profile %}
					<li> <a href="{% url 'fooodie:settingsprofilepic' %}"> Upload a profile Picture</a></li>
					<li><a href="{% url 'fooodie:addfoodphoto'%}">Upload a food plate</a></li>
					<li><a href="/fooodie/myprofile/settings/">Settings</a></li>
					{% else %}
						<strong>You're using a user that is NOT linked to a UserProfile, thus you have no profile picture options available</strong>
					{% endif %}
				</ul>
			</nav>
		</aside> <!-- END fooodie-ASIDE -->
		
		<div id="fooodie-main">
			<section class="ftco-section ftco-bread">
				<div class="container">
					<div class="row no-gutters slider-text justify-content-center align-items-center">
						<div class="col-md-8">
							<h1 class="bread">My Profile</h1>
						</div>
					</div>
				</div>
			</section>
			<h1>Upload food photo</h1>
		{% if added %}
			Fooodie says: <strong>Thank you for uploading a food photo!</strong>
			<a href="{% url 'fooodie:home' %}">Return to the homepage.</a><br />
		{% else %}
			<strong>Add a food photo here!</strong><br />
			<form id="food_pic_form" method="post" action="{% url 'fooodie:addfoodphoto' %}" enctype="multipart/form-data">
				{% csrf_token %}
				{{ food_pic_form.as_p }}
				<input type="submit" name="submit" value="Add food Pic"/>
			</form>
		{% endif %}
		</div><!-- END fooodie-MAIN -->
	</div><!-- END fooodie-PAGE -->
</section>

{% endblock %}

templates/fooodie/base.html

<!DOCTYPE html>
{% load staticfiles %}
{% load fooodie_template_tags %}

<html>
	<head lang="en">
		<meta charset="UTF-8">
		<meta name="description" content="">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


	
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">
		
		
		<title>
		
        Fooodie - {% block title_block %}{% endblock %}
		</title>
</head>

<body>

<!-- ***** Header Area Start ***** -->
    <header class="header_area clearfix" >
        <div class="container-fluid h-100">
            <div class="row h-100">
                <!-- Menu Area Start -->
                <div class="col-12 h-100">
                    <div class="menu_area h-100">
                        <nav class="navbar h-100 navbar-expand-lg align-items-center">
                            <!-- Logo -->
                            <a class="navbar-brand" href="{% url 'fooodie:home' %}"><img src="{% static 'images/logo.png' %}" alt="logo"></a>

                            <!-- Menu Area -->
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#fooodie-navbar" aria-controls="fooodie-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

                            <div class="collapse navbar-collapse justify-content-around" id="fooodie-navbar" style="font-family:'Codebold';">
                                <ul class="navbar-nav animated" id="nav" style = "max-width:100%">
                                    <li class="nav-item"><a class="nav-link" href="{% url 'fooodie:home' %}"><i class="fas fa-home"></i> Home</a></li>
									<li class="nav-item"><a class="nav-link" href="{% url 'fooodie:leaderboard' %}"><i class="fas fa-trophy"></i> Leaderboard</a></li>
									{% if user.is_authenticated %}
										<li class="nav-item"><a class="nav-link" href="{% url 'fooodie:myprofile' %}"><i class="far fa-user"></i> My profile</a></li>
										<li class="nav-item"><a class="nav-link" href="{% url 'fooodie:logout' %}"><i class="fas fa-sign-out-alt"></i> Log Out</a></li>
									{% else %}
                                    <li class="nav-item"><a class="nav-link" href="{% url 'fooodie:loginregister' %}"><i class="fas fa-sign-in-alt"></i> Login - SignUp</a></li>
                                    {% endif %}
                                </ul>
                                <!-- Search Form Area Start -->
									<form class="form-inline my-2 my-lg-1" action="{% url 'fooodie:usersearch' %}" style = "font-family: 'Arial';">
										<input
												class="form-control mr-sm-2" type="search"
												placeholder="Search" aria-label="Search"
												name='search' value="">
										<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
									</form>
                                </div>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
<!-- ***** Header Area End ***** -->

		{% block body_block %}
		{% endblock %}
</body>
<!-- ***** Footer Area Start ***** -->

    <footer class="footer-area clearfix">
        <!-- Fotter Bottom Area -->
        <div class="footer-bottom-area">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-12 h-100">
                        <div class="footer-bottom-content h-100 d-md-flex justify-content-between align-items-center">
                            <div class="copyright-text">
                                <p>
Copyright &copy;<script>document.write(new Date().getFullYear());</script> Fooodie revolutionary project all rights reserved
</p>
                            </div>
                            <div class="footer-social-info">
                                <li class="nav-item"><a class="nav-link" href="{% url 'fooodie:about' %}">About Us</a></li>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ***** Footer Area End ***** -->
<!--Scripts here so the page loades faster-->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <script src="{% static 'js/fooodie-ajax.js' %}"></script>
      <!-- All Plugins js -->
    <script src="{% static 'js/plugins.js' %}"></script>
    <!-- Active js -->
    <script src="{% static 'js/active.js' %}"></script>
		</body>
</html>

templates/fooodie/register.html
<!DOCTYPE>
{% load staticfiles %}
<html>
	<head lang="en">
		<meta charset="UTF-8" />
		<title> Foodie - 
		{% block title_block %} 
		Register 
		{% endblock %} 
		</title> 
<h1>THIS IS THE REGISTRATION TEMPLATE</h1>
	<body>
		<div>
			{% if registered %}
				<strong>Thank you for registering!</strong>
				<a href="{% url 'fooodie:home' %}">Return to the homepage.</a><br />
			{% else %}
				<strong>Register here!</strong><br />
				<form id="user_form" method="post" action="{% url 'fooodie:register' %}" enctype="multipart/form-data">
					{% csrf_token %}
					{{ user_form.as_p }}
					{{ profile_form.as_p }}
					<input type="submit" name="submit" value="Register" />
				</form>
			{% endif %}
</html>

templates/fooodie/settings.html
{% extends 'fooodie/base.html' %}
{% load static %}

	{% block title_block %}
		MyProfile
	{% endblock %}

<!--Just a layout, with placeholders still need actual obejcts-->
{% block body_block %}
<section class="section_padding_100_0 clearfix">
	<div id="fooodie-page">
		<a href="#" class="js-fooodie-nav-toggle fooodie-nav-toggle"><i></i></a>
		<aside id="fooodie-aside" role="complementary" class="text-center">
			{% if profile.picture %}
				<h1 id="fooodie-logo"><span class="img" style="background-image: url({{ profile.picture.url}});"></span>{{ user.username }}</h1>
			{% else %}
				<h1 id="fooodie-logo"><span class="img" style="background-image: url({% static 'images/defaultprofilefoto.jpg' %});"></span>{{ user.username }}</h1>
			{% endif %}
			<nav id="fooodie-main-menu" role="navigation">
				<ul>
					<li> <a href="{% url 'fooodie:settingsprofilepic' %}"> Upload a profile Picture</a></li>
					<li><a href="{% url 'fooodie:addfoodphoto'%}">Upload a food plate</a></li>
					<li><a href="{% url 'fooodie:settings' %}">Settings</a></li>
				</ul>
			</nav>
		</aside> <!-- END fooodie-ASIDE -->
		
		<div id="fooodie-main">
		
			<section class="ftco-bread">

						<div class="row no-gutters slider-text justify-content-center align-items-center" style = "position: relative; top: 0;">
							
								<h1 class="bread" style = "position: relative; top: 0; font-family:'Codebold';">My Profile - Settings</h1>
								
						</div>
			</section>
			<div class="section-heading text-center">
				<div class="tab-content py-4">
					<div class="tab-pane active">
						<h3 class="mb-3" style ="text-decoration: underline;">User Profile Settings</h3>
						<div class="row">
							<div class="col">
								<h6>Your username:</h6> {{ profile.user.username }}
								<p>
									<a class="nav-link-settings" href="{% url 'fooodie:settingsusername' %}">Change your username</a>
								</p>
								{% if profile.picture %}
									<h6>Your profile picture:</h6> <h1 id="fooodie-picture"><span class="img" style="background-image: url({{ profile.picture.url}});"></span></h1>
								{% else %}
									<h6>Your profile picture:</h6> You don't have a profile picture
								{% endif %}
								<p>
									<a class="nav-link-settings" href="{% url 'fooodie:settingsprofilepic' %}">Change your profile picture</a>
								</p>
								{% if profile.google %}
									<h6>Accounts made with google have no password nor an option to change your email.</h6> 
								{% else %}
									<h6>Your email:</h6> {{ profile.user.email }}
									<p>
										<a class="nav-link-settings" href="{% url 'fooodie:settingsemail' %}">Change your email</a>
									</p>
									<h6>Your password... Will not be displayed as that is very unsafe ;)</h6>
									<p>
										<a class="nav-link-settings" href="{% url 'fooodie:settingspassword' %}">Click here to change your password</a>
									</p>
								{% endif %}
								
								<span style = "color: red; font-weight: 700; font-size: 25px;">DELETE ACCOUNT:</span><br>
								<span style = "color: black; font-weight: 500;">IF YOU WISH TO DELETE YOUR ACCOUNT CLICK ON THE BUTTON BELOW. </span><br>
								
									
									<button class = "buttonDelete" onclick="document.getElementById('id01').style.display='block'">Delete your account</button>

									<div id="id01" class="modal">
									  <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
									  <form class="modal-content" action="/action_page.php">
										<div class="container">
										  <h1>DELETE ACCOUNT</h1>
										  <span style = "color: black; font-weight: 500;">ONCE DONE <strong>ALL</strong> YOUR PHOTOS AND VOTES WILL BE DELETED. YOUR PROGRESS HERE WILL DISSAPPEAR.</span> <br>
											<span style = "color: black; font-weight: 500;">WE'LL MISS YOU :(</span>

										  <div class="clearfix">
											<a   class="cancelbtn" href="{% url 'fooodie:settings' %}" >Keep posting amazing pictures</a>
											<span>    </span><span>    </span><span>    </span>
											<a  class="deletebtn" href="{% url 'fooodie:deleteaccount' %}">Delete my account</a>
										  </div>
										</div>
									  </form>
									</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div><!-- END fooodie-MAIN -->
	</div><!-- END fooodie-PAGE -->
</section>
{% endblock %}